//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constant
    {
        public int idConstant { get; set; }
        public Nullable<int> maxCustomer { get; set; }
        public Nullable<double> percent { get; set; }
    }
}
