//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class AccountRole : XPLiteObject
    {
        int fIdAccountRole;
        [Key(true)]
        [Persistent(@"idAccountRole")]
        public int IdAccountRole
        {
            get { return fIdAccountRole; }
            set { SetPropertyValue<int>(nameof(IdAccountRole), ref fIdAccountRole, value); }
        }
        string fDisplayName;
        [Indexed(Name = @"UQ__AccountR__32DE959A2146A8EB", Unique = true)]
        [Persistent(@"displayName")]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        [Association(@"AccountReferencesAccountRole")]
        public XPCollection<Account> Accounts { get { return GetCollection<Account>(nameof(Accounts)); } }
        [Association(@"EmployeeReferencesAccountRole")]
        public XPCollection<Employee> Employees { get { return GetCollection<Employee>(nameof(Employees)); } }
    }

}
