//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class Account : XPLiteObject
    {
        int fIdAccount;
        [Key(true)]
        [Persistent(@"idAccount")]
        public int IdAccount
        {
            get { return fIdAccount; }
            set { SetPropertyValue<int>(nameof(IdAccount), ref fIdAccount, value); }
        }
        AccountRole fIdAccountRole;
        [Persistent(@"idAccountRole")]
        [Association(@"AccountReferencesAccountRole")]
        public AccountRole IdAccountRole
        {
            get { return fIdAccountRole; }
            set { SetPropertyValue<AccountRole>(nameof(IdAccountRole), ref fIdAccountRole, value); }
        }
        string fUsername;
        [Indexed(Name = @"UQ__Account__F3DBC5723912CDCE", Unique = true)]
        [Persistent(@"username")]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPassword;
        [Persistent(@"password")]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        [Association(@"SalaryRecordReferencesAccount")]
        public XPCollection<SalaryRecord> SalaryRecords { get { return GetCollection<SalaryRecord>(nameof(SalaryRecords)); } }
    }

}
