//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class Bill : XPLiteObject
    {
        string fIdBill;
        [Key]
        [Size(64)]
        [Persistent(@"idBill")]
        public string IdBill
        {
            get { return fIdBill; }
            set { SetPropertyValue<string>(nameof(IdBill), ref fIdBill, value); }
        }
        Room fIdRoom;
        [Persistent(@"idRoom")]
        [Association(@"BillReferencesRoom")]
        public Room IdRoom
        {
            get { return fIdRoom; }
            set { SetPropertyValue<Room>(nameof(IdRoom), ref fIdRoom, value); }
        }
        Employee fIdEmployee;
        [Persistent(@"idEmployee")]
        [Association(@"BillReferencesEmployee")]
        public Employee IdEmployee
        {
            get { return fIdEmployee; }
            set { SetPropertyValue<Employee>(nameof(IdEmployee), ref fIdEmployee, value); }
        }
        Customer fIdCustomer;
        [Persistent(@"idCustomer")]
        [Association(@"BillReferencesCustomer")]
        public Customer IdCustomer
        {
            get { return fIdCustomer; }
            set { SetPropertyValue<Customer>(nameof(IdCustomer), ref fIdCustomer, value); }
        }
        DateTime fCheckIn;
        [Persistent(@"checkIn")]
        public DateTime CheckIn
        {
            get { return fCheckIn; }
            set { SetPropertyValue<DateTime>(nameof(CheckIn), ref fCheckIn, value); }
        }
        DateTime fCheckOut;
        [Persistent(@"checkOut")]
        public DateTime CheckOut
        {
            get { return fCheckOut; }
            set { SetPropertyValue<DateTime>(nameof(CheckOut), ref fCheckOut, value); }
        }
        decimal fTotalMoney;
        [Persistent(@"totalMoney")]
        public decimal TotalMoney
        {
            get { return fTotalMoney; }
            set { SetPropertyValue<decimal>(nameof(TotalMoney), ref fTotalMoney, value); }
        }
    }

}
