//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class Customer : XPLiteObject
    {
        int fIdCustomer;
        [Key]
        [Persistent(@"idCustomer")]
        public int IdCustomer
        {
            get { return fIdCustomer; }
            set { SetPropertyValue<int>(nameof(IdCustomer), ref fIdCustomer, value); }
        }
        string fPhone;
        [Indexed(Name = @"UQ__Customer__B43B145F90ECD75D", Unique = true)]
        [Size(20)]
        [Persistent(@"phone")]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fFullname;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"fullname")]
        public string Fullname
        {
            get { return fFullname; }
            set { SetPropertyValue<string>(nameof(Fullname), ref fFullname, value); }
        }
        string fGender;
        [Size(20)]
        [Persistent(@"gender")]
        [ColumnDbDefaultValue("('Others')")]
        public string Gender
        {
            get { return fGender; }
            set { SetPropertyValue<string>(nameof(Gender), ref fGender, value); }
        }
        string fAddress;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"address")]
        [ColumnDbDefaultValue("('Not provided')")]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        DateTime fDateOfBirth;
        [Persistent(@"dateOfBirth")]
        [ColumnDbDefaultValue("(NULL)")]
        public DateTime DateOfBirth
        {
            get { return fDateOfBirth; }
            set { SetPropertyValue<DateTime>(nameof(DateOfBirth), ref fDateOfBirth, value); }
        }
        string fIdCard;
        [Indexed(Name = @"UQ__Customer__8BA3E8F6742F95DC", Unique = true)]
        [Size(20)]
        [Persistent(@"idCard")]
        public string IdCard
        {
            get { return fIdCard; }
            set { SetPropertyValue<string>(nameof(IdCard), ref fIdCard, value); }
        }
        byte fType;
        [Persistent(@"type")]
        public byte Type
        {
            get { return fType; }
            set { SetPropertyValue<byte>(nameof(Type), ref fType, value); }
        }
        bool fIsDelete;
        [Persistent(@"isDelete")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDelete
        {
            get { return fIsDelete; }
            set { SetPropertyValue<bool>(nameof(IsDelete), ref fIsDelete, value); }
        }
        [Association(@"BillReferencesCustomer")]
        public XPCollection<Bill> Bills { get { return GetCollection<Bill>(nameof(Bills)); } }
    }

}
