//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class EmployeeRole : XPLiteObject
    {
        int fIdEmployeeRole;
        [Key(true)]
        [Persistent(@"idEmployeeRole")]
        public int IdEmployeeRole
        {
            get { return fIdEmployeeRole; }
            set { SetPropertyValue<int>(nameof(IdEmployeeRole), ref fIdEmployeeRole, value); }
        }
        string fDisplayName;
        [Indexed(Name = @"UQ__Employee__32DE959AE5C5FACD", Unique = true)]
        [Persistent(@"displayName")]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        [Association(@"EmployeeReferencesEmployeeRole")]
        public XPCollection<Employee> Employees { get { return GetCollection<Employee>(nameof(Employees)); } }
    }

}
