//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class ProductImportInfo : XPLiteObject
    {
        int fQuantity;
        [Persistent(@"quantity")]
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
        decimal fPrice;
        [Persistent(@"price")]
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(64)]
            [Persistent("idImport")]
            public string IdImport { get; set; }
            [Size(64)]
            [Persistent("idProduct")]
            public string IdProduct { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
