//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class Product : XPLiteObject
    {
        string fIdProduct;
        [Key]
        [Size(64)]
        [Persistent(@"idProduct")]
        public string IdProduct
        {
            get { return fIdProduct; }
            set { SetPropertyValue<string>(nameof(IdProduct), ref fIdProduct, value); }
        }
        string fDisplayName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"displayName")]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        string fUnit;
        [Size(20)]
        [Persistent(@"unit")]
        public string Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<string>(nameof(Unit), ref fUnit, value); }
        }
        decimal fPricePerUnit;
        [Persistent(@"pricePerUnit")]
        public decimal PricePerUnit
        {
            get { return fPricePerUnit; }
            set { SetPropertyValue<decimal>(nameof(PricePerUnit), ref fPricePerUnit, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"image")]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        int fQuantity;
        [Persistent(@"quantity")]
        [ColumnDbDefaultValue("((0))")]
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
        string fStatus;
        [Size(255)]
        [Persistent(@"status")]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        bool fIsDelete;
        [Persistent(@"isDelete")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDelete
        {
            get { return fIsDelete; }
            set { SetPropertyValue<bool>(nameof(IsDelete), ref fIsDelete, value); }
        }
    }

}
