//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class ProductImport : XPLiteObject
    {
        string fIdImport;
        [Key]
        [Size(64)]
        [Persistent(@"idImport")]
        public string IdImport
        {
            get { return fIdImport; }
            set { SetPropertyValue<string>(nameof(IdImport), ref fIdImport, value); }
        }
        Employee fIdEmployee;
        [Persistent(@"idEmployee")]
        [Association(@"ProductImportReferencesEmployee")]
        public Employee IdEmployee
        {
            get { return fIdEmployee; }
            set { SetPropertyValue<Employee>(nameof(IdEmployee), ref fIdEmployee, value); }
        }
        DateTime fDateImport;
        [Persistent(@"dateImport")]
        public DateTime DateImport
        {
            get { return fDateImport; }
            set { SetPropertyValue<DateTime>(nameof(DateImport), ref fDateImport, value); }
        }
        decimal fImportPrice;
        [Persistent(@"importPrice")]
        public decimal ImportPrice
        {
            get { return fImportPrice; }
            set { SetPropertyValue<decimal>(nameof(ImportPrice), ref fImportPrice, value); }
        }
    }

}
