//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class Room : XPLiteObject
    {
        int fIdRoom;
        [Key]
        [Persistent(@"idRoom")]
        public int IdRoom
        {
            get { return fIdRoom; }
            set { SetPropertyValue<int>(nameof(IdRoom), ref fIdRoom, value); }
        }
        string fDisplayName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"displayName")]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        string fType;
        [Size(50)]
        [Persistent(@"type")]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        decimal fPrice;
        [Persistent(@"price")]
        public decimal Price
        {
            get { return fPrice; }
            set { SetPropertyValue<decimal>(nameof(Price), ref fPrice, value); }
        }
        string fStatus;
        [Size(255)]
        [Persistent(@"status")]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"note")]
        [ColumnDbDefaultValue("('')")]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        bool fIsDelete;
        [Persistent(@"isDelete")]
        [ColumnDbDefaultValue("((0))")]
        public bool IsDelete
        {
            get { return fIsDelete; }
            set { SetPropertyValue<bool>(nameof(IsDelete), ref fIsDelete, value); }
        }
        [Association(@"BillReferencesRoom")]
        public XPCollection<Bill> Bills { get { return GetCollection<Bill>(nameof(Bills)); } }
    }

}
