//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class SalaryRecordInfo : XPLiteObject
    {
        string fIdSalaryRecord;
        [Size(64)]
        [Persistent(@"idSalaryRecord")]
        public string IdSalaryRecord
        {
            get { return fIdSalaryRecord; }
            set { SetPropertyValue<string>(nameof(IdSalaryRecord), ref fIdSalaryRecord, value); }
        }
        int fNumOfShift;
        [Persistent(@"numOfShift")]
        [ColumnDbDefaultValue("((0))")]
        public int NumOfShift
        {
            get { return fNumOfShift; }
            set { SetPropertyValue<int>(nameof(NumOfShift), ref fNumOfShift, value); }
        }
        int fNumOfFault;
        [Persistent(@"numOfFault")]
        [ColumnDbDefaultValue("((0))")]
        public int NumOfFault
        {
            get { return fNumOfFault; }
            set { SetPropertyValue<int>(nameof(NumOfFault), ref fNumOfFault, value); }
        }
        decimal fTotalSalary;
        [Persistent(@"totalSalary")]
        public decimal TotalSalary
        {
            get { return fTotalSalary; }
            set { SetPropertyValue<decimal>(nameof(TotalSalary), ref fTotalSalary, value); }
        }
        float fCoefficients;
        [Persistent(@"coefficients")]
        [ColumnDbDefaultValue("((1))")]
        public float Coefficients
        {
            get { return fCoefficients; }
            set { SetPropertyValue<float>(nameof(Coefficients), ref fCoefficients, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("idEmployee")]
            public int IdEmployee { get; set; }
            [Persistent("salaryMonth")]
            public DateTime SalaryMonth { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
