//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class SalaryTable : XPLiteObject
    {
        int fIdEmployeeRole;
        [Key]
        [Persistent(@"idEmployeeRole")]
        public int IdEmployeeRole
        {
            get { return fIdEmployeeRole; }
            set { SetPropertyValue<int>(nameof(IdEmployeeRole), ref fIdEmployeeRole, value); }
        }
        decimal fSalaryBase;
        [Persistent(@"salaryBase")]
        public decimal SalaryBase
        {
            get { return fSalaryBase; }
            set { SetPropertyValue<decimal>(nameof(SalaryBase), ref fSalaryBase, value); }
        }
        decimal fMoneyPerShift;
        [Persistent(@"moneyPerShift")]
        public decimal MoneyPerShift
        {
            get { return fMoneyPerShift; }
            set { SetPropertyValue<decimal>(nameof(MoneyPerShift), ref fMoneyPerShift, value); }
        }
        decimal fMoneyPerFault;
        [Persistent(@"moneyPerFault")]
        public decimal MoneyPerFault
        {
            get { return fMoneyPerFault; }
            set { SetPropertyValue<decimal>(nameof(MoneyPerFault), ref fMoneyPerFault, value); }
        }
        byte fStandardWorkDays;
        [Persistent(@"standardWorkDays")]
        public byte StandardWorkDays
        {
            get { return fStandardWorkDays; }
            set { SetPropertyValue<byte>(nameof(StandardWorkDays), ref fStandardWorkDays, value); }
        }
    }

}
