//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Hotel_JustFriend.Models.Hotel_JustFriend
{

    public partial class SalaryRecord : XPLiteObject
    {
        string fIdSalaryRecord;
        [Key]
        [Size(64)]
        [Persistent(@"idSalaryRecord")]
        public string IdSalaryRecord
        {
            get { return fIdSalaryRecord; }
            set { SetPropertyValue<string>(nameof(IdSalaryRecord), ref fIdSalaryRecord, value); }
        }
        Account fIdAccount;
        [Persistent(@"idAccount")]
        [Association(@"SalaryRecordReferencesAccount")]
        public Account IdAccount
        {
            get { return fIdAccount; }
            set { SetPropertyValue<Account>(nameof(IdAccount), ref fIdAccount, value); }
        }
        DateTime fSalaryRecordDate;
        [Persistent(@"salaryRecordDate")]
        public DateTime SalaryRecordDate
        {
            get { return fSalaryRecordDate; }
            set { SetPropertyValue<DateTime>(nameof(SalaryRecordDate), ref fSalaryRecordDate, value); }
        }
        decimal fTotal;
        [Persistent(@"total")]
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
    }

}
