//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentInvoice()
        {
            this.RentInvoiceInfoes = new HashSet<RentInvoiceInfo>();
        }
    
        public int idRentInvoice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<bool> purchase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInvoiceInfo> RentInvoiceInfoes { get; set; }
        public virtual Room Room { get; set; }
    }
}
