//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInvoiceInfo
    {
        public int IdRentInvoiceInfo { get; set; }
        public int IdRentInvoice { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RentInvoice RentInvoice { get; set; }
    }
}
