//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int idRevenue { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<decimal> RevenueType { get; set; }
    
        public virtual TypeRoom TypeRoom { get; set; }
    }
}
