//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRecordInfo
    {
        public string idSalaryRecord { get; set; }
        public int idEmployee { get; set; }
        public Nullable<int> numOfShift { get; set; }
        public Nullable<int> numOfFault { get; set; }
        public Nullable<decimal> totalSalary { get; set; }
        public System.DateTime salaryMonth { get; set; }
        public Nullable<float> coefficients { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalaryRecord SalaryRecord { get; set; }
    }
}
