//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_JustFriend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTable
    {
        public int idEmployeeRole { get; set; }
        public decimal salaryBase { get; set; }
        public decimal moneyPerShift { get; set; }
        public decimal moneyPerFault { get; set; }
        public byte standardWorkDays { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
